In [13]:
import pandas as pd


df = pd.read_csv(r"C:\Users\deepu\Downloads\archive (12)\diabetes.csv")


df["original"]


0       1
1       0
2       1
3       1
4       0
       ..
9049    0
9050    0
9051    0
9052    1
9053    0
Name: original, Length: 9054, dtype: int64

In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
import xgboost as xgb


In [15]:

df = df.dropna()  

X = df.drop('original', axis=1)  
y = df['original']  

X = pd.get_dummies(X)


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)


In [17]:
models = {
    'Logistic Regression': LogisticRegression(),
    'Random Forest': RandomForestClassifier(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'XGBoost': xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
}


In [18]:
results = {}

for name, model in models.items():
 
    model.fit(X_train, y_train)
    
 
    y_pred = model.predict(X_test)
    
 
    accuracy = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    
 
    results[name] = {
        'Accuracy': accuracy,
        'Confusion Matrix': cm,
        'Classification Report': report
    }
    
    print(f"{name} Accuracy: {accuracy}")
    print(f"{name} Confusion Matrix:\n{cm}")
    print(f"{name} Classification Report:\n{report}")
    print("\n" + "="*50 + "\n")


Logistic Regression Accuracy: 0.7736057426836003
Logistic Regression Confusion Matrix:
[[1050  129]
 [ 281  351]]
Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.89      0.84      1179
           1       0.73      0.56      0.63       632

    accuracy                           0.77      1811
   macro avg       0.76      0.72      0.73      1811
weighted avg       0.77      0.77      0.76      1811



Random Forest Accuracy: 0.9988956377691883
Random Forest Confusion Matrix:
[[1179    0]
 [   2  630]]
Random Forest Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1179
           1       1.00      1.00      1.00       632

    accuracy                           1.00      1811
   macro avg       1.00      1.00      1.00      1811
weighted avg       1.00      1.00      1.00      1811



Support Vector Machine Accuracy: 0.87410270568

C:\Users\deepu\anaconda3\Lib\site-packages\xgboost\data.py:364: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):


XGBoost Accuracy: 1.0
XGBoost Confusion Matrix:
[[1179    0]
 [   0  632]]
XGBoost Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1179
           1       1.00      1.00      1.00       632

    accuracy                           1.00      1811
   macro avg       1.00      1.00      1.00      1811
weighted avg       1.00      1.00      1.00      1811





In [19]:
model_comparison = pd.DataFrame({
    'Model': results.keys(),
    'Accuracy': [r['Accuracy'] for r in results.values()],
})

model_comparison = model_comparison.sort_values(by='Accuracy', ascending=False)
print(model_comparison)


                    Model  Accuracy
4                 XGBoost  1.000000
1           Random Forest  0.998896
3     K-Nearest Neighbors  0.996687
2  Support Vector Machine  0.874103
0     Logistic Regression  0.773606


In [20]:
xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')

xgb_model.fit(X_train, y_train)


C:\Users\deepu\anaconda3\Lib\site-packages\xgboost\data.py:364: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):


XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='mlogloss', gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_to_onehot=4, max_delta_step=0, max_depth=6,
              max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=0,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [21]:
y_pred = xgb_model.predict(X_test)
 
print("Predictions: ", y_pred)


Predictions:  [0 0 1 ... 0 0 1]


In [22]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)


Accuracy: 1.0000
Confusion Matrix:
 [[1179    0]
 [   0  632]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1179
           1       1.00      1.00      1.00       632

    accuracy                           1.00      1811
   macro avg       1.00      1.00      1.00      1811
weighted avg       1.00      1.00      1.00      1811



In [23]:
import pandas as pd
import numpy as np
import gradio as gr
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv(r"C:\Users\deepu\Downloads\archive (12)\diabetes.csv")  # Replace with your actual dataset path

df = df.dropna() 
X = df.drop('original', axis=1)  
y = df['original']  

X = pd.get_dummies(X)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train, y_train)
feature_labels=['no_Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']
def predict(*input_features):
    input_data = np.array(input_features).reshape(1, -1)  # Ensure input is in correct shape
    
    input_scaled = scaler.transform(input_data)
    
    prediction = xgb_model.predict(input_scaled)
    
    return "sugar positive🥺🥺🥺" if prediction[0] == 1 else "sugar negative😃😃😃"

interface = gr.Interface(fn=predict, outputs="text", live=True,flagging_options=["average ", "good prediction", "bad prediction"],
                        inputs = [
    gr.Checkbox(label="Pregnancies"),  # Checkbox for Pregnancies
    gr.Slider(minimum=0, maximum=200, step=1, label="Glucose"),  # Slider for Glucose
    gr.Slider(minimum=0, maximum=900, step=1, label="Insulin"),  # Slider for Insulin
    gr.Slider(minimum=10, maximum=70, step=0.1, label="BMI"),  # Slider for BMI
    gr.Slider(minimum=0.0, maximum=2.5, step=0.01, label="Diabetes Pedigree Function"),  # Slider for DiabetesPedigreeFunction
    gr.Slider(minimum=18, maximum=100, step=1, label="Age"),  # Slider for Age
    gr.Slider(minimum=0, maximum=100, step=1, label="Skin Thickness") ,
    gr.Slider(minimum=0, maximum=100, step=1, label="BloodPressure")# Slider for Skin Thickness
])

interface.launch(share=True)


C:\Users\deepu\anaconda3\Lib\site-packages\xgboost\data.py:364: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):


* Running on local URL:  http://127.0.0.1:7860
* Running on public URL: https://d03d25b6b2e694a53e.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


C:\Users\deepu\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\deepu\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\deepu\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\deepu\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\deepu\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\deepu\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid f

In [ ]:
pip install xgboost

In [ ]:
## pickleing the model file store it in the local directory

import pickle

In [15]:
pickle.dump(xgb_model,open("xg_boost.pkl","wb"))

In [16]:
a=pickle.load(open("xg_boost.pkl","rb"))

In [17]:
a.predict(X_test)

array([0, 0, 1, ..., 0, 0, 1])

In [31]:
X_test

array([[ 2.77266795, -0.46179483,  0.04843911, ...,  0.26831534,
        -0.67613323,  1.5964815 ],
       [-0.52737617, -0.30618348, -0.47008502, ..., -0.73255071,
        -0.39536423, -0.86085191],
       [-0.82738018, -0.58628392,  0.25584876, ...,  0.93138911,
        -0.54795608,  0.74912516],
       ...,
       [ 0.97264388, -0.05720531, -3.58122981, ..., -0.85765897,
        -0.80431038,  0.32544698],
       [ 1.87265592, -0.18169439, -3.58122981, ...,  0.40593443,
        -1.03319816, -0.3524381 ],
       [ 1.87265592, -0.39955029, -0.15897054, ...,  0.04312048,
        -0.61204466,  0.74912516]])